spring.application.name=aiStocksPredictor
server.port=${PORT:8080}

# Logging
logging.level.com.pxbt.dev=DEBUG

# Stock Market Data settings (Finnhub)
stock.data.interval=1d
stock.data.limit=500
finnhub.api.key=${FINNHUB_API_KEY:d6k4dhhr01qko8c3bg5gd6k4dhhr01qko8c3bg60}


# Reduce log file size and retention
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=3
logging.level.com.pxbt.dev.aiTradingCharts=DEBUG
logging.level.com.pxbt.dev=DEBUG
logging.level.root=INFO

# Spring specific logging
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# WebSocket noise reduction
logging.level.org.springframework.web.socket=WARN
logging.level.org.java_websocket=WARN

# WebClient noise
logging.level.org.springframework.web.reactive=WARN
logging.level.reactor.netty=WARN

# Binance API noise
logging.level.com.pxbt.dev.aiTradingCharts.Gateway=INFO

# Enable Actuator endpoints
management.endpoints.web.exposure.include=metrics,prometheus,health,info,env

# Enable metrics distribution for percentiles
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Optional: Configure specific percentiles
management.metrics.distribution.percentiles.http.server.requests=0.5,0.75,0.95,0.99

app.training.enabled=true